# Generated by Django 5.2.5 on 2025-08-31 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='favorites_f_user_id_645357_idx'), models.Index(fields=['pokemon_id'], name='favorites_f_pokemon_8beeb6_idx'), models.Index(fields=['-created_at'], name='favorites_f_created_49a632_idx')],
                'unique_together': {('user', 'pokemon_id')},
            },
        ),
    ]
