version: "3.9"

services:
  web:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8020:8000"              # -> http://localhost:8020
    volumes:
      - .:/app                   # Dev pohodlie: hot-reload a db.sqlite3 zostáva u teba v projekte
    # Ak nechceš hot-reload, volume vypusti.