version: "3.9"

services:
  web:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8020:8000"   # -> http://localhost:8020
    volumes:
      - .:/app