# Generated by Django 5.2.5 on 2025-09-01 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_comments', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', '-created_at'], name='community_t_team_id_6babdb_idx'), models.Index(fields=['author', '-created_at'], name='community_t_author__4ed971_idx')],
            },
        ),
    ]
