# Generated by Django 5.2.5 on 2025-09-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_teamcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamcomment',
            options={'ordering': ['-created_at'], 'permissions': [('can_moderate_comments', 'Can moderate (delete) team comments')]},
        ),
    ]
